# Generated by Django 3.2.5 on 2021-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='file',
        ),
        migrations.RemoveField(
            model_name='startapper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='startapper',
            name='file',
        ),
        migrations.RemoveField(
            model_name='startapper',
            name='title',
        ),
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(default='no bio...', max_length=400),
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('NewYork', 'NewYork')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/user_image'),
        ),
        migrations.AddField(
            model_name='startapper',
            name='bio',
            field=models.TextField(default='no bio...', max_length=400),
        ),
        migrations.AddField(
            model_name='startapper',
            name='country',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('NewYork', 'NewYork')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startapper',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/user_image'),
        ),
    ]
